name: CI - Churn MLOps

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:


jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # -------- Hugging Face authentication --------
    - name: Login to Hugging Face
      run: |
        python -c "from huggingface_hub import login; import os; login(token=os.environ['HF_TOKEN'])"
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}

    - name: Run preprocessing
      run: python src/preprocess.py

    - name: Train model
      run: python src/train.py

    - name: Evaluate model
      run: python src/evaluate.py

    # -------- Run batch predictions --------
    - name: Run batch predictions
      run: python src/batch_predict.py

    - name: Upload batch prediction results
      uses: actions/upload-artifact@v4
      with:
        name: churn_predictions
        path: new_test_data/predictions_output.csv

    # -------- Docker build --------
    - name: Build Docker image
      run: docker build -t churn-api .
